# Generated by Django 4.2 on 2023-12-27 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0010_auto_20201114_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Party', 'Party'), ('Seminar', 'Seminar'), ('Concert', 'Concert')], max_length=200),
        ),
        migrations.CreateModel(
            name='EventEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
